=== joaomrc/Sistema-de-Transporte-de-Mercadorias/json_schema/mercadoria.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Mercadoria",
    "type": "object",
    "properties": {
      "id": {
        "type": "integer"
      },
      "descricao": {
        "type": "string"
      },
      "origem": {
        "type": "string"
      },
      "destino": {
        "type": "string"
      },
      "peso": {
        "type": "number"
      }
    },
    "required": ["id", "descricao", "origem", "destino", "peso"]
  }

=== joaomrc/Sistema-de-Transporte-de-Mercadorias/mercadorias.json
[
    {
        "id": 1,
        "descricao": "Computadores portáteis",
        "origem": "Lisboa",
        "destino": "Porto",
        "peso": 120.5
    },
    {
        "id": 2,
        "descricao": "Cadeiras de escritório",
        "origem": "Braga",
        "destino": "Coimbra",
        "peso": 300.2
    },
    {
        "id": 5,
        "descricao": "Monitores LCD",
        "origem": "Faro",
        "destino": "Aveiro",
        "peso": 210
    },
    {
        "id": 6,
        "descricao": "Roupa",
        "origem": "Santarém",
        "destino": "Porto",
        "peso": 43.5
    },
    {
        "id": 7,
        "descricao": "Tecidos",
        "origem": "Bragança",
        "destino": "Alpiarça",
        "peso": 13.7
    },
    {
        "id": 8,
        "descricao": "Roupa de inverno",
        "origem": "Lisboa",
        "destino": "Porto",
        "peso": 120
    },
    {
        "id": 9,
        "descricao": "Loiças",
        "origem": "Faro",
        "destino": "Viseu",
        "peso": 63.1
    },
    {
        "id": 10,
        "descricao": "Móveis",
        "origem": "Beja",
        "destino": "Santarém",
        "peso": 110
    },
    {
        "id": 11,
        "descricao": "Materiais de construção",
        "origem": "Setúbal",
        "destino": "Évora",
        "peso": 980.5
    },
    {
        "id": 12,
        "descricao": "Materiais de construção",
        "origem": "Setúbal",
        "destino": "Évora",
        "peso": 980.5
    },
    {
        "id": 14,
        "descricao": "Impressoras 3D",
        "origem": "Lisboa",
        "destino": "Leiria",
        "peso": 75.5
    },
    {
        "id": 13,
        "descricao": "Livros escolares",
        "origem": "Lisboa",
        "destino": "Porto",
        "peso": 55
    },
    {
        "id": 15,
        "descricao": "Equipamento hospitalar",
        "origem": "Braga",
        "destino": "Coimbra",
        "peso": 140.5
    },
    {
        "id": 16,
        "descricao": "Electrodomésticos",
        "origem": "Aveiro",
        "destino": "Lisboa",
        "peso": 320
    },
    {
        "id": 17,
        "descricao": "Peças automóvel",
        "origem": "Porto",
        "destino": "Faro",
        "peso": 320.2
    },
    {
        "id": 18,
        "descricao": "Equipamento agrícola",
        "origem": "Guarda",
        "destino": "Bragança",
        "peso": 820.6
    },
    {
        "id": 19,
        "descricao": "Roupa e têxteis",
        "origem": "Leiria",
        "destino": "Setúbal",
        "peso": 96.2
    }
]

=== joaomrc/Sistema-de-Transporte-de-Mercadorias/exportado.json
[
    {
      "id": 1,
      "descricao": "Computadores portáteis",
      "origem": "Lisboa",
      "destino": "Porto",
      "peso": 120.5
    },
    {
      "id": 2,
      "descricao": "Cadeiras de escritório",
      "origem": "Braga",
      "destino": "Coimbra",
      "peso": 300.2
    },
    {
      "id": 3,
      "descricao": "Monitores LCD",
      "origem": "Faro",
      "destino": "Aveiro",
      "peso": 210.75
    },
    {
      "id": 4,
      "descricao": "Impressoras 3D",
      "origem": "Leiria",
      "destino": "Setúbal",
      "peso": 85.3
    },
    {
      "id": 5,
      "descricao": "Mesa de desenho",
      "origem": "Évora",
      "destino": "Viseu",
      "peso": 120
    },
    {
      "id": 6,
      "descricao": "Caixas de ferramentas",
      "origem": "Guimarães",
      "destino": "Funchal",
      "peso": 95.7
    }
  ]
